console.log("Working with conditional Statements");
var car = 'Subaru';
console.log("Is car == 'Subaru'? I predict True.");
console.log(car == 'Subaru');
console.log("Is car != 'Toyota'? I predict True.");
console.log(car != 'Toyota');
console.log("Is car == 'Toyota'? I predict False.");
console.log(car == 'Toyota');
console.log("Is car != 'Subaru'? I predict False.");
console.log(car != 'Subaru');
console.log("Is car >= 'Subaru'? I predict True.");
console.log(car >= 'Subaru');
console.log("Is car <= 'Subaru'? I predict True.");
console.log(car <= 'Subaru');
console.log("Is car < 'Subaru'? I predict False.");
console.log(car < 'Subaru');
console.log("Is car > 'Subaru'? I predict False.");
console.log(car > 'Subaru');
console.log("Is car !> 'Subaru'? I predict False.");
console.log(car > 'Subaru');
